### ISSUE TITLE
borked install/documentation

### ISSUE THREAD

**Issue by tttp** [TechToThePeople/proca-cli#2]
Hi,

so I tried to use it, git pull doesn't have anything working yet and the npm install path made weird things

also, do we REALLY need parcel? is this only to have "import" instead of "require" in that case, I vote to remove the extra js usual babel+packer insanity and stay close to node metal

as for where is the bin/how to use it, I think there is a more node way of doing that, but let's catch up later so I understand better what was the plan, ok?

**Comment by marcinkoziej** [comment]
Parcel brings all the ES2017 things so import is one, but more importantly, async/await which really hep to avoid the callback hell, and i think also destructuring (so you can do things like `array.map(({id, title}) => { ... })`

Ahhh. I made a mistake in package.json, it should not try to run parcel on install, just in dev mode!

**Comment by marcinkoziej** [comment]
Fixed. can yo ucheck? Please install with `npm i -g proca_cli`

**Comment by marcinkoziej** [comment]
Parcel is only  dev dependency, it is not leaded for the install!

**Comment by tttp** [comment]
oops, I pushed an unparcelised version

**Comment by tttp** [comment]
so now you can git pull and ./bin/proca-cli and voila

side node: why is this "proca_cli" for the package and proca-cli for the command? can't we have the same? or at least "proca_cli" for the package and "proca" as the command?

**Comment by marcinkoziej** [comment]
naming: nmpjs does not like names with hyphens, some JS code has problem with require'ing it, that's why. On the other hand, Unix commands rather use - then _

**Comment by marcinkoziej** [comment]
ESM - cool, let it be, simpler for this case. I have fixed it so proca_cli can also be required as module
